import Head from "next/head";
import styles from "../styles/Home.module.css";
import Sidebar from "../components/Sidebar";
import ConversationList from "../components/ConversationList";
import ChatView from "../components/ChatView";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Discord Blockchain app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        <Sidebar />
        <div className={styles.main}>
          <ConversationList />
          <ChatView />
        </div>
      </div>
    </div>
  );
}
